services:

    #----------------------------------------------------------------------------------------------
    # Subscribers
    #----------------------------------------------------------------------------------------------

    gdc_encryption.subscriber.aes:
        class: Gdc\EncryptionBundle\Subscriber\AesSubscriber
        public: false
        arguments:
            - '%gdc_encryption.aes_key%'
            - '@annotation_reader'
        tags:
            - { name: doctrine.event_subscriber }
